
[TagConfig]
	ITEM_PREFERENCE = ["minecraft", "emendatusenigmatica", "thermal", "mekanism", "immersiveengineering", "kubejs", "pneumaticcraft", "industrialforegoing", "botania", "quark", "pedestals"]

